<?php

/**
 * @file
 * daterange_argument.module
 */

use Drupal\Core\Url;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function daterange_argument_help($route_name, RouteMatchInterface $route_match) {

  switch ($route_name) {
    case 'help.page.daterange_argument':
      $options = [
        ':one' => Url::fromRoute('daterange_argument.settings')->toString(),
      ];
      $help = t('You must first add contextual filters in the advanced section of the Views UI before they appear on this <a href=":one">configuration</a> page.', $options);
      return $help;

    default:
  }
}
